// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coltpedcrfibsozxvgvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvbHRwZWRjcmZpYnNvenh2Z3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzQwOTQsImV4cCI6MjA1NTgxMDA5NH0.T-KCLemrnykSiGqddr_KpN5Y1HO2IRlUVBEGOQJWfAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);